// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"mbook/webook/comment/grpc"
	"mbook/webook/comment/repository"
	"mbook/webook/comment/repository/dao"
	"mbook/webook/comment/service"
	"mbook/webook/pkg/logger"
)

// Injectors from wire.go:

func InitGRPCServer() *grpc.CommentServiceServer {
	gormDB := InitTestDB()
	commentDAO := dao.NewCommentDAO(gormDB)
	loggerV1 := logger.NewNoOpLogger()
	commentRepository := repository.NewCommentRepo(commentDAO, loggerV1)
	commentService := service.NewCommentSvc(commentRepository)
	commentServiceServer := grpc.NewGrpcServer(commentService)
	return commentServiceServer
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewCommentDAO, repository.NewCommentRepo, service.NewCommentSvc, grpc.NewGrpcServer)

var thirdProvider = wire.NewSet(logger.NewNoOpLogger, InitTestDB)
