// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"mbook/webook/follow/grpc"
	"mbook/webook/follow/ioc"
	"mbook/webook/follow/repository"
	"mbook/webook/follow/repository/dao"
	"mbook/webook/follow/service"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	followRelationDao := dao.NewGORMFollowRelationDAO(db)
	followRelationRepository := repository.NewFollowRelationRepository(followRelationDao)
	followRelationService := service.NewFollowRelationService(followRelationRepository)
	followRelationServiceServer := grpc.NewFollowRelationServiceServer(followRelationService)
	server := ioc.InitGRPCxServer(followRelationServiceServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMFollowRelationDAO, repository.NewFollowRelationRepository, service.NewFollowRelationService, grpc.NewFollowRelationServiceServer)

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitLogger)
